[package]
name = "cwatch"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
notify = "6.1"
anyhow = "1.0"
walkdir = "2.4"
sha2 = "0.10"
similar = "2.2"
